/-
Copyright (c) 2026 The Compfiles Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Li Xuanji
-/

import Mathlib

import ProblemExtraction

problem_file { tags := [.Algebra] }

/-!
# International Mathematical Competition 1998, Problem 2 (Day 1)

Let `n ≥ 2` and let `π₁ ∈ S_n` with `π₁ ≠ id`. Decide for which `n` the
following statement holds:

  *For every such `π₁`, there exists `π₂ ∈ S_n` such that the two-element
  set `{π₁, π₂}` generates `S_n`.*

The statement holds for `n = 3` and `n = 5`, but fails for `n = 4`.

## Solution sketch

* `n = 3`: if `π₁` is a transposition, take `π₂` a 3-cycle (the two
  generate `S_3`). If `π₁` is a 3-cycle, take `π₂` a transposition.

* `n = 4` (counterexample): take `π₁ = (1 2)(3 4)`. The Klein four-group
  `K = {id, (12)(34), (13)(24), (14)(23)}` is normal in `S_4` and the
  quotient `S_4 / K ≅ S_3` is not cyclic. If `⟨π₁, π₂⟩ = S_4`, then
  `S_4 / K = ⟨π₂ K⟩` would be cyclic, a contradiction.

* `n = 5`: case analysis on the cycle type of `π₁`. In each of the six
  possible cycle types, an explicit `π₂` is exhibited (see e.g. the
  IMC 1998 official solution).

## Status

The statement is formalized for general `n`, with all three cases left
as `sorry` (the `n=3` and `n=5` cases require explicit constructions,
the `n=4` case requires the normality of the Klein four-group and
non-cyclicity of `S_3`).
-/

namespace Imc1998P2

open Equiv

/--
The property "every non-identity `π₁ ∈ S_n` has a partner `π₂` such that
`{π₁, π₂}` generates `S_n`."
-/
def HasUniversalPartner (n : ℕ) : Prop :=
  ∀ π₁ : Perm (Fin n), π₁ ≠ 1 →
    ∃ π₂ : Perm (Fin n),
      Subgroup.closure ({π₁, π₂} : Set (Perm (Fin n))) = ⊤

/-- The property holds for `n = 3`. -/
problem imc1998_p2_n3 : HasUniversalPartner 3 := by
  -- For `n = 3`: if `π₁` is a transposition, take `π₂` a 3-cycle;
  -- if `π₁` is a 3-cycle, take `π₂` a transposition.
  -- TODO: case-analyze `π₁` (only 5 non-identity elements in `S_3`)
  -- and exhibit the witness in each case.
  sorry

/-- The property fails for `n = 4`: the double transposition `(1 2)(3 4)`
has no universal partner. -/
problem imc1998_p2_n4 : ¬ HasUniversalPartner 4 := by
  -- Counterexample: `π₁ = (0 1)(2 3)` (Klein four-group element).
  -- For any `π₂`, the closure `⟨π₁, π₂⟩` lies inside the preimage of
  -- `⟨π₂ K⟩` under the quotient `S_4 → S_4/K`. Since `S_4/K ≅ S_3` is not
  -- cyclic, `⟨π₂ K⟩ ≠ S_4/K`, hence `⟨π₁, π₂⟩ ≠ S_4`.
  -- TODO: this requires:
  --   1. Defining the Klein four-group `K ≤ S_4` (as a subgroup, normal).
  --   2. The quotient map `S_4 →* S_4 / K`.
  --   3. The isomorphism `S_4 / K ≅ S_3`, or a direct argument that the
  --      quotient is non-cyclic of order 6.
  sorry

/-- The property holds for `n = 5`. -/
problem imc1998_p2_n5 : HasUniversalPartner 5 := by
  -- Case analysis by cycle type of `π₁` in `S_5`. Cycle types of
  -- non-identity elements: (2), (3), (3,2), (4), (2,2), (5).
  -- The official IMC solution gives explicit `π₂` in each case:
  --   * (12)         pair with (12345);
  --   * (123)        pair with (124)(35);
  --   * (123)(45)    pair with (124);
  --   * (1234)       pair with (12345);
  --   * (12)(34)     pair with (1354);
  --   * (12345)      pair with (12).
  -- TODO: in each case verify that the closure is `⊤` (e.g. using the
  -- fact that `A_5` is generated by 3-cycles, and an odd element plus
  -- `A_5` give all of `S_5`).
  sorry

end Imc1998P2
