/-
Copyright (c) 2026 The Compfiles Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Li Xuanji
-/

import Mathlib

import ProblemExtraction

problem_file { tags := [.Algebra] }

/-!
# International Mathematical Competition 1996, Problem 9 (Day 2, Problem 3)

Let `G ≤ GL₂(ℝ)` be the subgroup generated by
`A = ⟨⟨2, 0⟩, ⟨0, 1⟩⟩` and `B = ⟨⟨1, 1⟩, ⟨0, 1⟩⟩`.
Let `H = {M ∈ G : M₁₁ = M₂₂ = 1}`.
(a) Show that `H` is abelian.
(b) Show that `H` is not finitely generated.

## Proof outline (official solution)

**(a)** Every element of `G` is upper triangular with diagonal entries
`2^a` and `1` for some `a ∈ ℤ` (proved by induction over a word in
`A`, `B`, `A⁻¹`, `B⁻¹`). Hence elements of `H` have the form
`M(x) = ⟨⟨1, x⟩, ⟨0, 1⟩⟩`. Direct computation
`M(x) · M(y) = M(x + y)` shows `H` is abelian (and isomorphic, as a
group, to the additive subgroup `{x ∈ ℝ : M(x) ∈ G} ≤ ℝ`).

**(b)** All entries of every word in `A, B, A⁻¹, B⁻¹` are dyadic
rationals (i.e. of the form `p / 2^k`). In particular the
upper-right entry of any element of `H` is dyadic. Conversely, for
every `n ∈ ℕ`, `M(1 / 2ⁿ)` lies in `H` because
`A⁻ⁿ B Aⁿ = ⟨⟨1, 1/2ⁿ⟩, ⟨0, 1⟩⟩`.

If `H` were finitely generated by `M(x₁), …, M(x_r)` with each
`xᵢ = pᵢ / 2^{kᵢ}`, then every element of `H` would have its upper
right entry in `(1 / 2^N) · ℤ` where `N = max kᵢ`. But
`1 / 2^{N+1}` is in `H` and not of that form — contradiction.

## Status

This file contains the formal statement together with the basic
infrastructure (the matrix `M(x)`, the subgroup `G`, the subgroup `H`,
the parametrisation of `H` by reals). The full combinatorial argument
characterising elements of `G` is left as `sorry`.

-/

namespace Imc1996P9

open Matrix

/-- `M x` is the unipotent matrix `⟨⟨1, x⟩, ⟨0, 1⟩⟩`, viewed as an
element of `GL₂(ℝ)`. -/
noncomputable def M (x : ℝ) : GL (Fin 2) ℝ :=
  GeneralLinearGroup.mkOfDetNeZero !![1, x; 0, 1] (by simp [det_fin_two])

/-- The diagonal generator `A = diag(2,1)`. -/
noncomputable def A : GL (Fin 2) ℝ :=
  GeneralLinearGroup.mkOfDetNeZero !![2, 0; 0, 1] (by simp [det_fin_two])

/-- The unipotent generator `B = ⟨⟨1, 1⟩, ⟨0, 1⟩⟩`. -/
noncomputable def B : GL (Fin 2) ℝ := M 1

/-- The subgroup `G ≤ GL₂(ℝ)` generated by `A` and `B`. -/
noncomputable def G : Subgroup (GL (Fin 2) ℝ) :=
  Subgroup.closure {A, B}

/-- The "trace‐one" subset `H = {g ∈ G : g₁₁ = g₂₂ = 1}`. -/
noncomputable def H : Subgroup (GL (Fin 2) ℝ) where
  carrier := {g : GL (Fin 2) ℝ |
    g ∈ G ∧ (g : Matrix (Fin 2) (Fin 2) ℝ) 0 0 = 1
          ∧ (g : Matrix (Fin 2) (Fin 2) ℝ) 1 1 = 1}
  one_mem' := by
    refine ⟨G.one_mem, ?_, ?_⟩ <;>
      · show (1 : Matrix (Fin 2) (Fin 2) ℝ) _ _ = 1
        simp
  mul_mem' := by
    rintro x y ⟨hxG, hx00, hx11⟩ ⟨hyG, hy00, hy11⟩
    refine ⟨G.mul_mem hxG hyG, ?_, ?_⟩
    · -- Need extra info: from G all elements are upper triangular.
      -- We axiomatise this via `sorry` below.
      sorry
    · sorry
  inv_mem' := by
    rintro x ⟨hxG, hx00, hx11⟩
    refine ⟨G.inv_mem hxG, ?_, ?_⟩
    · sorry
    · sorry

snip begin

/-- `M x · M y = M (x + y)`. This is direct matrix multiplication. -/
lemma M_mul_M (x y : ℝ) : M x * M y = M (x + y) := by
  apply Units.ext
  show (M x : Matrix (Fin 2) (Fin 2) ℝ) * (M y : Matrix (Fin 2) (Fin 2) ℝ)
       = (M (x + y) : Matrix (Fin 2) (Fin 2) ℝ)
  unfold M
  simp only [Matrix.GeneralLinearGroup.val_mkOfDetNeZero]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two, add_comm]

/-- Inverse of `M x`: `(M x)⁻¹ = M (-x)`. -/
lemma M_inv (x : ℝ) : (M x)⁻¹ = M (-x) := by
  rw [eq_comm, eq_inv_iff_mul_eq_one, M_mul_M]
  show M (-x + x) = 1
  rw [neg_add_cancel]
  apply Units.ext
  show (M 0 : Matrix (Fin 2) (Fin 2) ℝ) = 1
  unfold M
  simp only [Matrix.GeneralLinearGroup.val_mkOfDetNeZero]
  ext i j
  fin_cases i <;> fin_cases j <;> simp

/-- `B = M 1`, by definition. -/
lemma B_eq_M_one : B = M 1 := rfl

/-- The conjugation identity `A⁻¹ * M x * A = M (x / 2)`. Direct
computation. -/
lemma A_inv_M_A (x : ℝ) : A⁻¹ * M x * A = M (x / 2) := by
  -- Reduce to a matrix equation.
  apply Units.ext
  show ((A⁻¹ : GL (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ)
        * (M x : Matrix (Fin 2) (Fin 2) ℝ) * (A : Matrix (Fin 2) (Fin 2) ℝ)
        = (M (x / 2) : Matrix (Fin 2) (Fin 2) ℝ)
  -- Compute `A⁻¹` directly: it equals `mkOfDetNeZero !![1/2, 0; 0, 1] _`.
  have hA_inv : ((A⁻¹ : GL (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ)
        = !![(1 : ℝ)/2, 0; 0, 1] := by
    have h1 : (A : Matrix (Fin 2) (Fin 2) ℝ) * !![(1 : ℝ)/2, 0; 0, 1] = 1 := by
      unfold A
      simp only [Matrix.GeneralLinearGroup.val_mkOfDetNeZero]
      ext i j; fin_cases i <;> fin_cases j <;>
        simp [Matrix.mul_apply, Fin.sum_univ_two]
    rw [Matrix.GeneralLinearGroup.coe_inv]
    exact (Matrix.inv_eq_right_inv h1)
  rw [hA_inv]
  unfold A M
  simp only [Matrix.GeneralLinearGroup.val_mkOfDetNeZero]
  ext i j
  fin_cases i <;> fin_cases j <;>
    first | (simp [Matrix.mul_apply, Fin.sum_univ_two]; ring) | simp [Matrix.mul_apply, Fin.sum_univ_two]

snip end

/-- **(a)** The subgroup `H` is abelian. -/
problem imc1996_p9_part_a : ∀ x y : H, x * y = y * x := by
  -- Every element of `H` has the form `M(x)`, and `M(a) M(b) = M(a+b) = M(b) M(a)`.
  -- This requires the structural lemma "every element of G is upper triangular",
  -- which is left as `sorry` in the construction of `H`.
  sorry

/-- **(b)** The subgroup `H` is not finitely generated. -/
problem imc1996_p9_part_b :
    ¬ ∃ S : Finset (GL (Fin 2) ℝ), (∀ s ∈ S, s ∈ H)
        ∧ Subgroup.closure (S : Set (GL (Fin 2) ℝ)) = H := by
  -- Sketch:
  -- 1. Show that for each n, M(1/2^n) ∈ H, via M(1/2^n) = (A^{-n}) * B * (A^n).
  --    Iterating `A_inv_M_A`: `A^{-n} * M 1 * A^n = M (1/2^n)`.
  -- 2. Show that all entries of any element of G are dyadic rationals.
  -- 3. Hence the upper‐right entries of any finite generating set lie in
  --    `(1/2^N) · ℤ` for some `N`, and hence so do the entries of every
  --    element of the subgroup they generate.
  -- 4. But `1/2^{N+1}` is the (1,2)-entry of `M(1/2^{N+1}) ∈ H`, not in
  --    `(1/2^N) · ℤ`.
  sorry

end Imc1996P9
