/-
Copyright (c) 2026 The Compfiles Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Li Xuanji
-/

import Mathlib.Tactic

import ProblemExtraction

problem_file { tags := [.Algebra] }

/-!
# International Mathematical Competition 2005, Problem 6
(First day, Problem 6)

For a group `G` and a natural number `m`, let `G(m)` denote the subgroup of
`G` generated by all `m`-th powers. Prove that if `G(m)` and `G(n)` are
both commutative, then `G(gcd(m, n))` is also commutative.

## Proof sketch

Let `d = gcd(m, n)`. By Bezout, `G(d)` equals the subgroup generated by
`m`-th powers and `n`-th powers together. By
`Subgroup.isMulCommutative_closure`, it suffices to show that every pair of
generators commutes. Two `m`-th powers commute (since `G(m)` is abelian),
and similarly for `n`-th powers. For a mixed pair `a^m, b^n`, introduce
the commutator `z = a^{-m} b^{-n} a^m b^n`. Using the identity
`(g⁻¹ h g)^k = g⁻¹ h^k g`, one shows `z = (a⁻¹)^m (b^{-n} a b^n)^m ∈ G(m)`
and `z = ((a^m)⁻¹ b⁻¹ a^m)^n (b)^n ∈ G(n)`. Hence `z` lies in both
(commutative) subgroups, so it commutes with both `a^m` and `b^n`.
An induction gives `(a^m)^j · b^n = b^n · (a^m)^j · z^j`. Taking
`j = n/d`, the element `a^{mn/d} = (a^{m/d})^n` lies in `G(n)`, so it
commutes with `b^n`; this forces `z^{n/d} = 1`. Symmetrically
`z^{m/d} = 1`, and since `gcd(m/d, n/d) = 1` we conclude `z = 1`.
-/

namespace Imc2005P6

variable {G : Type*} [Group G]

/-- The subgroup generated by all `m`-th powers. -/
def Gp (G : Type*) [Group G] (m : ℕ) : Subgroup G :=
  Subgroup.closure {x | ∃ g : G, x = g ^ m}

-- snip begin

/-- Every `m`-th power lies in `Gp G m`. -/
lemma pow_mem_Gp (m : ℕ) (g : G) : g ^ m ∈ Gp G m :=
  Subgroup.subset_closure ⟨g, rfl⟩

/-- If `d ∣ m`, then every `m`-th power is a `d`-th power, so `Gp G m ≤ Gp G d`. -/
lemma Gp_mono_of_dvd {d m : ℕ} (hdm : d ∣ m) : Gp G m ≤ Gp G d := by
  rw [Gp]
  refine (Subgroup.closure_le _).mpr ?_
  rintro x ⟨g, rfl⟩
  obtain ⟨k, rfl⟩ := hdm
  rw [mul_comm, pow_mul]
  exact pow_mem_Gp d (g ^ k)

/-- Conjugation of a power: `a⁻¹ · b^k · a = (a⁻¹ · b · a)^k`. -/
lemma conj_pow (a b : G) (k : ℕ) : a⁻¹ * b ^ k * a = (a⁻¹ * b * a) ^ k := by
  induction k with
  | zero => simp
  | succ k ih =>
    rw [pow_succ, pow_succ, ← ih]
    group

/-- `z := a^{-m} · b^{-n} · a^m · b^n` is a commutator that lies in both
`Gp G m` and `Gp G n`. -/
lemma commutator_mem_both (m n : ℕ) (a b : G) :
    (a ^ m)⁻¹ * (b ^ n)⁻¹ * a ^ m * b ^ n ∈ Gp G m ∧
    (a ^ m)⁻¹ * (b ^ n)⁻¹ * a ^ m * b ^ n ∈ Gp G n := by
  refine ⟨?_, ?_⟩
  · -- z = (a⁻¹)^m · (b^{-n} · a · b^n)^m
    have hconj := conj_pow (b ^ n) a m
    have hz : (a ^ m)⁻¹ * (b ^ n)⁻¹ * a ^ m * b ^ n
            = (a⁻¹) ^ m * ((b ^ n)⁻¹ * a * b ^ n) ^ m := by
      rw [← hconj]
      group
    rw [hz]
    exact Subgroup.mul_mem _ (pow_mem_Gp m _) (pow_mem_Gp m _)
  · -- z = ((a^m)⁻¹ · b⁻¹ · a^m)^n · b^n
    have hconj := conj_pow (a ^ m) b⁻¹ n
    have hz : (a ^ m)⁻¹ * (b ^ n)⁻¹ * a ^ m * b ^ n
            = ((a ^ m)⁻¹ * b⁻¹ * a ^ m) ^ n * b ^ n := by
      rw [← hconj]
      group
    rw [hz]
    exact Subgroup.mul_mem _ (pow_mem_Gp n _) (pow_mem_Gp n _)

/-- Iteration: if `z` commutes with `a^m`, then
`(a^m)^j · b^n = b^n · (a^m)^j · z^j` where `a^m · b^n = b^n · a^m · z`. -/
lemma iter_comm (a b : G) (m n : ℕ)
    (z : G) (hz_def : z = (a ^ m)⁻¹ * (b ^ n)⁻¹ * a ^ m * b ^ n)
    (hz_am : z * a ^ m = a ^ m * z) :
    ∀ j : ℕ, (a ^ m) ^ j * b ^ n = b ^ n * (a ^ m) ^ j * z ^ j := by
  have hrearr : a ^ m * b ^ n = b ^ n * a ^ m * z := by
    rw [hz_def]; group
  -- z commutes with (a^m)^j for all j
  have hz_amj : ∀ j : ℕ, z * (a ^ m) ^ j = (a ^ m) ^ j * z := by
    intro j
    induction j with
    | zero => simp
    | succ j ih =>
      calc z * (a ^ m) ^ (j + 1)
          = (z * (a ^ m) ^ j) * a ^ m := by rw [pow_succ]; group
        _ = ((a ^ m) ^ j * z) * a ^ m := by rw [ih]
        _ = (a ^ m) ^ j * (z * a ^ m) := by group
        _ = (a ^ m) ^ j * (a ^ m * z) := by rw [hz_am]
        _ = (a ^ m) ^ (j + 1) * z := by rw [pow_succ]; group
  -- z^j commutes with a^m.
  have hzj_am : ∀ j : ℕ, z ^ j * a ^ m = a ^ m * z ^ j := by
    intro j
    induction j with
    | zero => simp
    | succ j ih =>
      calc z ^ (j + 1) * a ^ m
          = z ^ j * (z * a ^ m) := by rw [pow_succ]; group
        _ = z ^ j * (a ^ m * z) := by rw [hz_am]
        _ = (z ^ j * a ^ m) * z := by group
        _ = (a ^ m * z ^ j) * z := by rw [ih]
        _ = a ^ m * z ^ (j + 1) := by rw [pow_succ]; group
  intro j
  induction j with
  | zero => simp
  | succ j ih =>
    calc (a ^ m) ^ (j + 1) * b ^ n
        = (a ^ m) ^ j * (a ^ m * b ^ n) := by rw [pow_succ]; group
      _ = (a ^ m) ^ j * (b ^ n * a ^ m * z) := by rw [hrearr]
      _ = ((a ^ m) ^ j * b ^ n) * (a ^ m * z) := by group
      _ = (b ^ n * (a ^ m) ^ j * z ^ j) * (a ^ m * z) := by rw [ih]
      _ = b ^ n * (a ^ m) ^ j * ((z ^ j * a ^ m) * z) := by group
      _ = b ^ n * (a ^ m) ^ j * ((a ^ m * z ^ j) * z) := by rw [hzj_am]
      _ = b ^ n * (a ^ m) ^ (j + 1) * z ^ (j + 1) := by
            rw [pow_succ (a^m), pow_succ z]; group

/-- The key lemma: `a^m` and `b^n` commute when `Gp G m` and `Gp G n` are abelian. -/
lemma a_m_comm_b_n (m n : ℕ) (a b : G) (hm : IsMulCommutative (Gp G m))
    (hn : IsMulCommutative (Gp G n)) : a ^ m * b ^ n = b ^ n * a ^ m := by
  set z : G := (a ^ m)⁻¹ * (b ^ n)⁻¹ * a ^ m * b ^ n with hz_def
  obtain ⟨hz_m, hz_n⟩ := commutator_mem_both m n a b
  -- z commutes with a^m (both in Gp G m, abelian).
  have hz_am : z * a ^ m = a ^ m * z := by
    have := hm
    exact setLike_mul_comm hz_m (pow_mem_Gp m a)
  -- z commutes with b^n.
  have hz_bn : z * b ^ n = b ^ n * z := by
    have := hn
    exact setLike_mul_comm hz_n (pow_mem_Gp n b)
  -- Enough to show z = 1.
  suffices hzeq : z = 1 by
    -- z = 1 means (a^m)⁻¹ (b^n)⁻¹ a^m b^n = 1, so a^m b^n = b^n a^m.
    have hz1 : (a ^ m)⁻¹ * (b ^ n)⁻¹ * a ^ m * b ^ n = 1 := hz_def ▸ hzeq
    calc a ^ m * b ^ n
        = b ^ n * a ^ m * ((a ^ m)⁻¹ * (b ^ n)⁻¹ * a ^ m * b ^ n) := by group
      _ = b ^ n * a ^ m * 1 := by rw [hz1]
      _ = b ^ n * a ^ m := mul_one _
  -- Now show z = 1.
  -- Use iter_comm with j = n / d to get z^(n/d) = 1.
  -- Use symmetric version with j = m / d to get z^(m/d) = 1.
  -- Combine using gcd(m/d, n/d) = 1.
  set d := Nat.gcd m n with hd_def
  -- Case on whether both m, n are zero (then gcd = 0, everything trivial actually z needs m=0 case).
  by_cases hm0 : m = 0
  · -- a^m = a^0 = 1, so z = 1 directly.
    subst hm0
    simp [hz_def]
  by_cases hn0 : n = 0
  · subst hn0
    simp [hz_def]
  have hm_pos : 0 < m := Nat.pos_of_ne_zero hm0
  have hn_pos : 0 < n := Nat.pos_of_ne_zero hn0
  have hd_pos : 0 < d := Nat.gcd_pos_of_pos_left _ hm_pos
  -- Step 1: z^(n/d) = 1.
  -- Take j = n/d. Then (a^m)^(n/d) = a^(m*(n/d)) = a^(m*n/d) = (a^(m/d))^n ∈ Gp G n.
  have hiter_j := iter_comm a b m n z hz_def hz_am
  -- Need (a^m)^(n/d) * b^n = b^n * (a^m)^(n/d), because both in Gp G n.
  have hmn_d : m * (n / d) = (m / d) * n := by
    have hdm : d ∣ m := Nat.gcd_dvd_left m n
    have hdn : d ∣ n := Nat.gcd_dvd_right m n
    have hm_eq : m / d * d = m := Nat.div_mul_cancel hdm
    have hn_eq : n / d * d = n := Nat.div_mul_cancel hdn
    have : m * (n / d) = (m / d * d) * (n / d) := by rw [hm_eq]
    rw [this]
    rw [show (m / d * d) * (n / d) = (m / d) * (d * (n / d)) from by ring]
    rw [show d * (n / d) = (n / d) * d from by ring, hn_eq]
  have h_an : (a ^ m) ^ (n / d) ∈ Gp G n := by
    -- (a^m)^(n/d) = a^(m*(n/d)) = a^((m/d)*n) = (a^(m/d))^n
    rw [← pow_mul, hmn_d, pow_mul]
    exact pow_mem_Gp n _
  have h_comm_n : (a ^ m) ^ (n / d) * b ^ n = b ^ n * (a ^ m) ^ (n / d) := by
    have := hn
    exact setLike_mul_comm h_an (pow_mem_Gp n b)
  -- From hiter_j (n/d): (a^m)^(n/d) * b^n = b^n * (a^m)^(n/d) * z^(n/d)
  have h1 : (a ^ m) ^ (n / d) * b ^ n = b ^ n * (a ^ m) ^ (n / d) * z ^ (n / d) := hiter_j (n / d)
  have hz_nd : z ^ (n / d) = 1 := by
    have heq : b ^ n * (a ^ m) ^ (n / d) * z ^ (n / d) = b ^ n * (a ^ m) ^ (n / d) := by
      rw [← h1, h_comm_n]
    -- Cancel from left: z^(n/d) = 1.
    have := heq
    have h' : b ^ n * (a ^ m) ^ (n / d) * z ^ (n / d) = b ^ n * (a ^ m) ^ (n / d) * 1 := by
      rw [mul_one]; exact heq
    exact mul_left_cancel h'
  -- Step 2: z^(m/d) = 1, symmetrically.
  -- (a^m)^(m/d) would be a^(m^2/d) which is m-th power directly. But we need something else.
  -- Actually, iterate: b^n * (a^m)^j vs (a^m)^j * b^n? We need to redo: b^n * a^m = a^m * b^n * z⁻¹.
  -- Better: use iteration on the b side.
  -- From a^m * b^n = b^n * a^m * z, we also have: b^n = (a^m)⁻¹ * b^n * a^m * z, i.e.,
  -- "b^n and a^m up to z". Alternative: define w = [b^n, a^m] = (b^n)⁻¹ (a^m)⁻¹ b^n a^m.
  -- Then the roles of m,n are swapped.
  -- We'll set up the same iteration with m and n swapped by applying the lemma symmetrically.
  -- Instead: w := (b^n)⁻¹ * (a^m)⁻¹ * b^n * a^m. Note w = z⁻¹ conjugated... actually:
  -- z = a⁻ᵐ b⁻ⁿ aᵐ bⁿ, so z⁻¹ = b⁻ⁿ a⁻ᵐ bⁿ aᵐ = w. So w = z⁻¹.
  have hw_def : ((b ^ n)⁻¹ * (a ^ m)⁻¹ * b ^ n * a ^ m) = z⁻¹ := by
    rw [hz_def]; group
  -- Using iter_comm with (m, n, a, b) → (n, m, b, a): we get
  -- (b^n)^j * a^m = a^m * (b^n)^j * w^j.
  have hz_ab : z * b ^ n = b ^ n * z := hz_bn
  have hiter_j' := iter_comm b a n m z⁻¹ hw_def.symm ?_
  · -- Take j = m/d.
    have hmn_d' : n * (m / d) = (n / d) * m := by
      have := hmn_d
      -- swap m and n in hmn_d: same argument.
      have hdm : d ∣ m := Nat.gcd_dvd_left m n
      have hdn : d ∣ n := Nat.gcd_dvd_right m n
      have hm_eq : m / d * d = m := Nat.div_mul_cancel hdm
      have hn_eq : n / d * d = n := Nat.div_mul_cancel hdn
      calc n * (m / d) = (n / d * d) * (m / d) := by rw [hn_eq]
        _ = (n / d) * (d * (m / d)) := by ring
        _ = (n / d) * ((m / d) * d) := by rw [show d * (m / d) = (m / d) * d from by ring]
        _ = (n / d) * m := by rw [hm_eq]
    have h_bm : (b ^ n) ^ (m / d) ∈ Gp G m := by
      rw [← pow_mul, hmn_d', pow_mul]
      exact pow_mem_Gp m _
    have h_comm_m : (b ^ n) ^ (m / d) * a ^ m = a ^ m * (b ^ n) ^ (m / d) := by
      have := hm
      exact setLike_mul_comm h_bm (pow_mem_Gp m a)
    have h2 : (b ^ n) ^ (m / d) * a ^ m
            = a ^ m * (b ^ n) ^ (m / d) * (z⁻¹) ^ (m / d) := hiter_j' (m / d)
    have h_zinv_md : (z⁻¹) ^ (m / d) = 1 := by
      have heq : a ^ m * (b ^ n) ^ (m / d) * (z⁻¹) ^ (m / d)
                = a ^ m * (b ^ n) ^ (m / d) := by
        rw [← h2, h_comm_m]
      have h' : a ^ m * (b ^ n) ^ (m / d) * (z⁻¹) ^ (m / d)
              = a ^ m * (b ^ n) ^ (m / d) * 1 := by rw [mul_one]; exact heq
      exact mul_left_cancel h'
    have hz_md : z ^ (m / d) = 1 := by
      have : z ^ (m / d) = ((z⁻¹) ^ (m / d))⁻¹ := by group
      rw [this, h_zinv_md, inv_one]
    -- Now combine: gcd(m/d, n/d) = 1, and z^(m/d) = z^(n/d) = 1.
    have hcop : Nat.Coprime (m / d) (n / d) := by
      unfold Nat.Coprime
      have : Nat.gcd (m / d) (n / d) * d = Nat.gcd m n := by
        conv_rhs => rw [show m = (m / d) * d from (Nat.div_mul_cancel (Nat.gcd_dvd_left m n)).symm,
                        show n = (n / d) * d from (Nat.div_mul_cancel (Nat.gcd_dvd_right m n)).symm]
        rw [Nat.gcd_mul_right]
      have hd_ne : d ≠ 0 := hd_pos.ne'
      have hd_eq : Nat.gcd m n = d := hd_def.symm
      rw [hd_eq] at this
      -- gcd(m/d, n/d) * d = d, so gcd(m/d, n/d) = 1 (using d ≠ 0).
      have := Nat.eq_of_mul_eq_mul_right hd_pos
        (show Nat.gcd (m / d) (n / d) * d = 1 * d by rw [one_mul]; exact this)
      exact this
    -- Using orderOf: orderOf z divides m/d and n/d, which are coprime, so orderOf z = 1.
    have hord_md : orderOf z ∣ (m / d) := orderOf_dvd_iff_pow_eq_one.mpr hz_md
    have hord_nd : orderOf z ∣ (n / d) := orderOf_dvd_iff_pow_eq_one.mpr hz_nd
    have hord_1 : orderOf z ∣ 1 := by
      rw [← hcop]
      exact Nat.dvd_gcd hord_md hord_nd
    have : orderOf z = 1 := Nat.dvd_one.mp hord_1
    exact orderOf_eq_one_iff.mp this
  · -- Need to show z⁻¹ commutes with b^n: z * b^n = b^n * z so z⁻¹ * b^n = b^n * z⁻¹.
    have : z⁻¹ * b ^ n = b ^ n * z⁻¹ := by
      have := hz_bn
      calc z⁻¹ * b ^ n = z⁻¹ * (b ^ n * z) * z⁻¹ := by group
        _ = z⁻¹ * (z * b ^ n) * z⁻¹ := by rw [← hz_bn]
        _ = b ^ n * z⁻¹ := by group
    exact this

-- snip end

problem imc2005_p6 (G : Type*) [Group G] (m n : ℕ)
    (hm : IsMulCommutative (Gp G m))
    (hn : IsMulCommutative (Gp G n)) :
    IsMulCommutative (Gp G (Nat.gcd m n)) := by
  set d := Nat.gcd m n with hd_def
  have hGd_eq : Gp G d =
      Subgroup.closure ({x | ∃ g : G, x = g ^ m} ∪ {x | ∃ g : G, x = g ^ n}) := by
    apply le_antisymm
    · rw [Gp]
      refine (Subgroup.closure_le _).mpr ?_
      rintro x ⟨a, rfl⟩
      have hbez : (d : ℤ) = m * Nat.gcdA m n + n * Nat.gcdB m n := Nat.gcd_eq_gcd_ab m n
      have had : a ^ d = (a ^ Nat.gcdA m n) ^ m * (a ^ Nat.gcdB m n) ^ n := by
        have h1 : a ^ (d : ℤ) = (a ^ Nat.gcdA m n) ^ m * (a ^ Nat.gcdB m n) ^ n := by
          rw [hbez, zpow_add,
              show (m : ℤ) * Nat.gcdA m n = Nat.gcdA m n * (m : ℤ) from by ring,
              show (n : ℤ) * Nat.gcdB m n = Nat.gcdB m n * (n : ℤ) from by ring,
              zpow_mul, zpow_mul, zpow_natCast, zpow_natCast]
        have h2 : a ^ (d : ℤ) = a ^ d := zpow_natCast a d
        rw [← h2]; exact h1
      rw [had]
      exact Subgroup.mul_mem _
        (Subgroup.subset_closure (Or.inl ⟨_, rfl⟩))
        (Subgroup.subset_closure (Or.inr ⟨_, rfl⟩))
    · refine (Subgroup.closure_le _).mpr ?_
      rintro x (⟨g, rfl⟩ | ⟨g, rfl⟩)
      · exact Gp_mono_of_dvd (Nat.gcd_dvd_left m n) (pow_mem_Gp m g)
      · exact Gp_mono_of_dvd (Nat.gcd_dvd_right m n) (pow_mem_Gp n g)
  rw [hGd_eq]
  refine Subgroup.isMulCommutative_closure ?_
  rintro x (⟨a, rfl⟩ | ⟨a, rfl⟩) y (⟨b, rfl⟩ | ⟨b, rfl⟩)
  · exact setLike_mul_comm (pow_mem_Gp m a) (pow_mem_Gp m b)
  · exact a_m_comm_b_n m n a b hm hn
  · exact a_m_comm_b_n n m a b hn hm
  · exact setLike_mul_comm (pow_mem_Gp n a) (pow_mem_Gp n b)

end Imc2005P6
