/-
Copyright (c) 2026 The Compfiles Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Li Xuanji
-/

import Mathlib

import ProblemExtraction

problem_file { tags := [.Algebra] }

/-!
# International Mathematical Competition 2009, Problem 10
(Day 2, Problem 5)

Let `M` be the vector space of `m × p` real matrices. For a vector subspace
`S ⊆ M`, denote by `δ(S)` the dimension of the vector space generated by all
columns of all matrices in `S`.

Say that a vector subspace `T ⊆ M` is a *covering matrix space* if
`⋃_{A ∈ T, A ≠ 0} ker A = ℝ^p`.

Such a `T` is *minimal* if it does not contain a proper vector subspace
`S ⊂ T` which is also a covering matrix space.

(a) Let `T` be a minimal covering matrix space and let `n = dim T`.
Prove that `δ(T) ≤ n choose 2`.

(b) Prove that for every positive integer `n` we can find `m` and `p`, and a
minimal covering matrix space `T` as above such that `dim T = n` and
`δ(T) = n choose 2`.

The mathematical proof outline:
(a) In any covering subspace `S`, find `A ∈ S` with `rk A ≤ dim S - 1`.
Take a minimal subspace `S₀ ⊆ S`, fix a hyperplane `S' ⊂ S₀`. By
minimality, `S'` is not covering, so there is `u` with `τ(u) ≠ 0` for all
nonzero `τ ∈ S'`. The space `V = S'(u)` has dimension `s - 1`. There is
`A ∈ S₀ ∖ S'` with `Au = 0` (since `S₀` is covering). One shows
`Im A ⊂ V`, otherwise a generic perturbation yields a non-covering
contradiction. Iterate this to get a decomposition with the binomial bound.

(b) Take rows indexed by pairs `(i,j)` with `1 ≤ i < j ≤ n`. For
`u ∈ ℝⁿ`, let `A(u)` have entries `A(u)_{(i,j),k} = u_i` if `k = j`,
`-u_j` if `k = i`, and `0` otherwise. Then `ker A(u) = ℝ·u`, so
`T = {A(u) : u ∈ ℝⁿ}` is minimal covering, and the columns hit each
standard basis vector in `ℝ^{n choose 2}`.
-/

namespace Imc2009P10

open Matrix LinearMap Submodule

/-- A subspace `T` of `m × p` real matrices is a *covering matrix space* if
the union of kernels of nonzero elements equals all of `ℝ^p`. We phrase this
in matrix-space form: every `v : Fin p → ℝ` lies in the kernel of some
nonzero matrix `A ∈ T` (viewed as the linear map `mulVec`). -/
def IsCovering {m p : ℕ} (T : Submodule ℝ (Matrix (Fin m) (Fin p) ℝ)) : Prop :=
  ∀ v : Fin p → ℝ, ∃ A : Matrix (Fin m) (Fin p) ℝ,
    A ∈ T ∧ A ≠ 0 ∧ A.mulVec v = 0

/-- A covering matrix space `T` is *minimal* if no proper subspace of `T` is
also covering. -/
def IsMinimalCovering {m p : ℕ} (T : Submodule ℝ (Matrix (Fin m) (Fin p) ℝ)) :
    Prop :=
  IsCovering T ∧ ∀ S : Submodule ℝ (Matrix (Fin m) (Fin p) ℝ),
    S ≤ T → S ≠ T → ¬ IsCovering S

/-- The "column span" `δ(T)`: the dimension of the subspace of `ℝ^m` spanned
by all columns of all matrices in `T`. We define the column span as the
submodule of `ℝ^m` generated by the set of all columns of all `A ∈ T`. -/
noncomputable def colSpan {m p : ℕ}
    (T : Submodule ℝ (Matrix (Fin m) (Fin p) ℝ)) :
    Submodule ℝ (Fin m → ℝ) :=
  Submodule.span ℝ {v : Fin m → ℝ | ∃ A ∈ T, ∃ j : Fin p, v = fun i => A i j}

/-- `δ(T)` is the dimension of the column span of `T`. -/
noncomputable def delta {m p : ℕ}
    (T : Submodule ℝ (Matrix (Fin m) (Fin p) ℝ)) : ℕ :=
  Module.finrank ℝ (colSpan T)

/-- The binomial coefficient `n choose 2`. -/
def binom2 (n : ℕ) : ℕ := n.choose 2

snip begin

/-- For a minimal covering subspace `S₀ ⊆ T` of dimension `s`, every
hyperplane `S' ⊂ S₀` of dimension `s - 1` is not covering (used in proof
of part (a)). This is a direct consequence of minimality. -/
lemma not_covering_of_lt_minimal {m p : ℕ}
    (S₀ S' : Submodule ℝ (Matrix (Fin m) (Fin p) ℝ))
    (hS₀ : IsMinimalCovering S₀)
    (hS'lt : S' < S₀) :
    ¬ IsCovering S' := by
  intro hcov
  exact hS₀.2 S' (le_of_lt hS'lt) (ne_of_lt hS'lt) hcov

snip end

/-- Statement of IMC 2009 Problem 10.

The mathematical proof outline:

**Part (a)**: Use the key claim that in any covering subspace `S`, we can
find `A ∈ S` with `rk A ≤ dim S - 1`. Iterate to decompose
`T = Z₀ ⊕ Z₁ ⊕ ⋯` and the column span as `W₀ ⊕ W₁ ⊕ ⋯` with
`dim Wᵢ ≤ n - 1 - i`, summing to `≤ n choose 2`.

**Part (b)**: Use the explicit construction with rows indexed by
pairs `(i,j)`, `i < j`, and `A(u)_{(i,j),k}` defined as above. -/
problem imc2009_p10 :
    -- Part (a): every minimal covering matrix space T satisfies δ(T) ≤ binom(n, 2)
    (∀ {m p : ℕ} (T : Submodule ℝ (Matrix (Fin m) (Fin p) ℝ)),
      IsMinimalCovering T →
      delta T ≤ binom2 (Module.finrank ℝ T)) ∧
    -- Part (b): for every n ≥ 1, there exist m, p and a minimal covering T
    -- with dim T = n and δ(T) = binom(n, 2)
    (∀ n : ℕ, 0 < n →
      ∃ (m p : ℕ) (T : Submodule ℝ (Matrix (Fin m) (Fin p) ℝ)),
        IsMinimalCovering T ∧
        Module.finrank ℝ T = n ∧
        delta T = binom2 n) := by
  -- TODO: full proof. The proof is delicate linear-algebra extremal:
  --
  -- (a) Key lemma: in a covering matrix space S, ∃ A ∈ S with rk A ≤ dim S - 1.
  --     Proof: let S₀ ⊆ S be a minimal covering subspace, dim S₀ = s.
  --     Take S' ⊂ S₀ of dim s - 1. By minimality S' is not covering, so
  --     ∃ u with τ(u) ≠ 0 for all 0 ≠ τ ∈ S'. Let V = S'·u (dim s-1). Some
  --     A ∈ S₀ ∖ S' has Au = 0 (since S₀ covers); show Im A ⊂ V.
  --     If Av ∉ V, define f_α : S₀ → ℝ^m, (τ + βA) ↦ τ(u + αv) + βA·v.
  --     f_0 has rank s, so f_α has rank s for all but finitely many α,
  --     yielding ker f_α = 0 and contradicting minimality.
  --     Then iterate: decompose T = Z₀ ⊕ Z₁ ⊕ ⋯, columns = W₀ ⊕ W₁ ⊕ ⋯,
  --     dim Wᵢ ≤ n - 1 - i; summing gives δ(T) ≤ (n-1) + (n-2) + ⋯ = C(n,2).
  --
  -- (b) Explicit example: rows indexed by pairs (i,j), 1 ≤ i < j ≤ n.
  --     A(u)_{(i,j),k} = u_i if k = j; -u_j if k = i; 0 otherwise.
  --     Then ker A(u) = ℝ·u, so T = {A(u) : u ∈ ℝⁿ} is covering.
  --     Minimality: any A(u) ∈ S forces ℝ·u ⊆ ⋃ ker(B), so dim S ≥ n.
  --     Columns of A(eᵢ) at index j realize standard basis vector in
  --     ℝ^{C(n,2)}, so δ(T) = C(n,2).
  refine ⟨?_, ?_⟩
  · intro m p T hT
    sorry
  · intro n hn
    sorry

end Imc2009P10
