/-
Copyright (c) 2026 The Compfiles Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Li Xuanji
-/

import Mathlib.Tactic

import ProblemExtraction

problem_file { tags := [.Algebra] }

/-!
# International Mathematical Competition 2024, Problem 4

Let `g` and `h` be two distinct elements of a group `G`, and let `n` be a
positive integer. Consider a sequence `w = (w₁, w₂, …)` which is not
eventually periodic and where each `wᵢ` is either `g` or `h`. Denote by
`H` the subgroup of `G` generated by all elements of the form
`w_k · w_{k+1} · … · w_{k+n-1}` with `k ≥ 1`. Prove that `H` does not
depend on the choice of the sequence `w` (but may depend on `n`).
-/

namespace Imc2024P4

open scoped Pointwise

variable {G : Type*} [Group G]

/-- A sequence `w : ℕ → G` is eventually periodic if there exist `N` and
`p > 0` such that `w (k + p) = w k` for all `k ≥ N`. -/
def EventuallyPeriodic (w : ℕ → G) : Prop :=
  ∃ N p : ℕ, 0 < p ∧ ∀ k ≥ N, w (k + p) = w k

/-- The `n`-gram at index `k` of the sequence `w` is the product
`w k · w (k+1) · … · w (k + n - 1)`. -/
def ngram (w : ℕ → G) (n k : ℕ) : G :=
  ((List.range n).map (fun i => w (k + i))).prod

/-- The subgroup generated by all `n`-grams of the sequence `w`. -/
noncomputable def ngramSubgroup (w : ℕ → G) (n : ℕ) : Subgroup G :=
  Subgroup.closure {x | ∃ k : ℕ, x = ngram w n k}

/-- The product of a `{g,h}`-word of length `n` indexed by a Boolean function
(true ↦ `g`, false ↦ `h`). -/
def ghWord (g h : G) (n : ℕ) (s : Fin n → Bool) : G :=
  ((List.finRange n).map (fun i => if s i then g else h)).prod

/-- The subgroup generated by all `{g,h}`-words of length `n`. -/
noncomputable def ghSubgroup (g h : G) (n : ℕ) : Subgroup G :=
  Subgroup.closure {x | ∃ s : Fin n → Bool, x = ghWord g h n s}

/-- Every `n`-gram of a sequence with values in `{g,h}` is a `{g,h}`-word. -/
lemma ngram_mem_ghSubgroup (g h : G) (n : ℕ) (w : ℕ → G)
    (hw_vals : ∀ k, w k = g ∨ w k = h) (k : ℕ) :
    ngram w n k ∈ ghSubgroup g h n := by
  classical
  apply Subgroup.subset_closure
  -- Pick the boolean indicator: true if w (k+i) = g else false (it must be h).
  refine ⟨fun i => decide (w (k + i.val) = g), ?_⟩
  unfold ngram ghWord
  -- Convert the `List.finRange n` product to a `List.range n` product via `(·.val)`.
  rw [show (List.finRange n).map (fun i : Fin n =>
        if decide (w (k + i.val) = g) then g else h)
      = (List.range n).map (fun i =>
        if decide (w (k + i) = g) then g else h) by
      conv_lhs => rw [show (fun i : Fin n => if decide (w (k + i.val) = g) then g else h)
        = (fun i => if decide (w (k + i) = g) then g else h) ∘ (·.val) from rfl]
      rw [← List.map_map, List.map_coe_finRange_eq_range]]
  congr 1
  apply List.map_congr_left
  intro i hi
  by_cases hg : w (k + i) = g
  · simp [hg]
  · have hh : w (k + i) = h := (hw_vals (k + i)).resolve_left hg
    simp [hh]

/-- Easy direction: `ngramSubgroup w n ≤ ghSubgroup g h n`. -/
lemma ngramSubgroup_le_ghSubgroup (g h : G) (n : ℕ) (w : ℕ → G)
    (hw_vals : ∀ k, w k = g ∨ w k = h) :
    ngramSubgroup w n ≤ ghSubgroup g h n := by
  unfold ngramSubgroup
  rw [Subgroup.closure_le]
  rintro x ⟨k, rfl⟩
  exact ngram_mem_ghSubgroup g h n w hw_vals k

/-- Hard direction (Lemma in the official solution, applied at `j = n`):
For any non-eventually-periodic `{g,h}`-sequence `w`, every `{g,h}`-word of
length `n` lies in `ngramSubgroup w n`. The proof in the official solution
uses pigeonhole on `(n-1)`-suffixes, non-periodicity to find a position where
two such matching suffixes diverge, and induction on the prefix length. -/
lemma ghSubgroup_le_ngramSubgroup (g h : G) (hgh : g ≠ h) (n : ℕ) (hn : 0 < n)
    (w : ℕ → G) (hw_vals : ∀ k, w k = g ∨ w k = h)
    (hw_np : ¬ EventuallyPeriodic w) :
    ghSubgroup g h n ≤ ngramSubgroup w n := by
  -- TODO: Formalize the inductive argument from the official solution.
  -- Sketch:
  --   By pigeonhole on `(n-1)`-grams of `w`, there exist `k < ℓ` with
  --     `(w_{k+1}, …, w_{k+n-1}) = (w_{ℓ+1}, …, w_{ℓ+n-1})`.
  --   Non-periodicity yields `m > 0` with `w_{k+m} ≠ w_{ℓ+m}`; necessarily `m ≥ n`.
  --   For each `j = 1, …, n` and `a, b ∈ X_j` (length-j {g,h}-words),
  --     by induction on `j`, `a⁻¹ b ∈ ngramSubgroup w n`.
  --   Applying to `j = n` gives the result.
  sorry

problem imc2024_p4 (G : Type*) [Group G] (g h : G) (hgh : g ≠ h) (n : ℕ)
    (hn : 0 < n) (w w' : ℕ → G)
    (hw_vals : ∀ k, w k = g ∨ w k = h)
    (hw'_vals : ∀ k, w' k = g ∨ w' k = h)
    (hw_np : ¬ EventuallyPeriodic w)
    (hw'_np : ¬ EventuallyPeriodic w') :
    ngramSubgroup w n = ngramSubgroup w' n := by
  -- Both subgroups equal `ghSubgroup g h n`.
  apply le_antisymm <;>
    [skip; skip] <;>
    · refine le_trans (ngramSubgroup_le_ghSubgroup g h n _ ‹_›) ?_
      exact ghSubgroup_le_ngramSubgroup g h hgh n hn _ ‹_› ‹_›

end Imc2024P4
