/-
Copyright (c) 2026 The Compfiles Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Li Xuanji
-/

import Mathlib

import ProblemExtraction

problem_file { tags := [.Algebra] }

/-!
# International Mathematical Competition 2011, Problem 10
(= IMC 2011 Day 2, Problem 5)

Let `F = A_0 A_1 … A_n` be a convex polygon in the plane. For `1 ≤ k ≤ n - 1`,
define the operation `f_k` that replaces `F` with the polygon
`A_0 … A_{k-1} A'_k A_{k+1} … A_n`, where `A'_k` is the reflection of `A_k`
across the perpendicular bisector of `A_{k-1} A_{k+1}`.

Prove that `(f_1 ∘ f_2 ∘ ⋯ ∘ f_{n-1})^n (F) = F`, assuming all intermediate
polygons are convex.

## Proof outline (official solution)

The maps `f_i` are rational maps; it suffices to verify the identity on a
neighborhood of the regular polygon.

Verify the Coxeter relations of the symmetric group `S_n`:
* (i) `f_i ∘ f_i = id`,
* (ii) `f_i ∘ f_j = f_j ∘ f_i` for `|i - j| ≥ 2`,
* (iii) `(f_i ∘ f_{i+1})^3 = id`.

Relation (i) holds because reflection is an involution. Relation (ii) is clear
since the moves on disjoint vertex triples commute. For (iii), one observes
that `f_i` and `f_{i+1}` permute the consecutive side lengths
`|A_{i-1} A_i|, |A_i A_{i+1}|, |A_{i+1} A_{i+2}|` of the quadrilateral
`A_{i-1} A_i A_{i+1} A_{i+2}` while preserving the sums of opposite angles
of that quadrilateral. With fixed sides and these sums fixed, the quadrilateral
is determined; after `(f_i ∘ f_{i+1})^3` the side lengths return to the
original cyclic order, so the quadrilateral is restored.

These are the Coxeter relations of `S_n` with generators `σ_i = (i, i+1)`.
Hence the group generated by the `f_i` is a quotient of `S_n`, and in `S_n`
we have `(σ_1 σ_2 ⋯ σ_{n-1})^n = (1 2 ⋯ n)^n = id`. Therefore
`(f_1 ∘ ⋯ ∘ f_{n-1})^n = id`.
-/

namespace Imc2011P10

open EuclideanGeometry

/-- The Euclidean plane as `EuclideanSpace ℝ (Fin 2)`. -/
abbrev Plane := EuclideanSpace ℝ (Fin 2)

/-- A polygon with `n + 1` vertices in the plane is encoded as a function
`Fin (n + 1) → Plane`. -/
abbrev Polygon (n : ℕ) := Fin (n + 1) → Plane

/-- Reflection of a point `P` across the perpendicular bisector of `A` and `B`.
Concretely, if `M = (A + B) / 2` is the midpoint and `v = B - A` is the
direction of `AB`, then the perpendicular bisector is the affine hyperplane
through `M` orthogonal to `v`. The reflection sends `P` to
`P - 2 * ⟪P - M, v⟫ / ⟪v, v⟫ * v` when `A ≠ B`; when `A = B`, the bisector
is undefined and we set the reflection to be the identity. -/
noncomputable def reflectPerpBisector (A B P : Plane) : Plane :=
  if A = B then P
  else
    let M : Plane := (1 / 2 : ℝ) • (A + B)
    let v : Plane := B - A
    P - (2 * inner ℝ (P - M) v / inner ℝ v v) • v

/-- The operation `f_k` on a polygon: reflect vertex `k` across the
perpendicular bisector of vertices `k - 1` and `k + 1`. We require
`1 ≤ k` and `k ≤ n - 1` (so that `k - 1` and `k + 1` are valid indices).
For indices outside this range we leave the polygon unchanged. -/
noncomputable def fOp {n : ℕ} (k : ℕ) (F : Polygon n) : Polygon n := fun i =>
  if h : 1 ≤ k ∧ k + 1 ≤ n ∧ (i : ℕ) = k then
    have hkm : k - 1 < n + 1 := by omega
    have hkp : k + 1 < n + 1 := by omega
    reflectPerpBisector (F ⟨k - 1, hkm⟩) (F ⟨k + 1, hkp⟩) (F i)
  else F i

/-- Apply `fOp` for the indices `1, 2, …, m`, in the order
`fOp 1 ∘ fOp 2 ∘ ⋯ ∘ fOp m` (rightmost first). -/
noncomputable def fCompUpTo (n : ℕ) : ℕ → Polygon n → Polygon n
  | 0, F => F
  | m + 1, F => fOp 1 (fCompUpTo n m (fOp (m + 1) F))

-- A cleaner alternative: iterate from the rightmost index down to 1.

/-- The composition `f_1 ∘ f_2 ∘ ⋯ ∘ f_{n-1}`, applied to a polygon
with `n + 1` vertices (so that the moves involved are `fOp 1, …, fOp (n-1)`). -/
noncomputable def fComp (n : ℕ) (F : Polygon n) : Polygon n :=
  fCompUpTo n (n - 1) F

/-- Convexity predicate for a polygon: the vertices, taken in cyclic order,
form the boundary of a strictly convex region. Equivalently, all consecutive
turning angles (signed) are of the same sign and nonzero. We use a simple
formulation via cross products. -/
def IsConvex {n : ℕ} (F : Polygon n) : Prop :=
  ∀ i : Fin (n + 1),
    let A := F i
    let B := F ⟨((i : ℕ) + 1) % (n + 1), Nat.mod_lt _ (by omega)⟩
    let C := F ⟨((i : ℕ) + 2) % (n + 1), Nat.mod_lt _ (by omega)⟩
    -- The signed area of triangle `ABC` is positive (cross product condition).
    0 < (B 0 - A 0) * (C 1 - A 1) - (B 1 - A 1) * (C 0 - A 0)

/--
**IMC 2011 P10.** Let `F = A_0 A_1 … A_n` be a convex polygon. With the moves
`f_k` defined above, `(f_1 ∘ ⋯ ∘ f_{n-1})^n (F) = F`, provided every
intermediate polygon obtained while applying the iteration remains convex.

We state the conclusion in the form: applying `fComp n` exactly `n` times
to `F` returns `F`. The convexity of intermediate polygons is encoded as the
hypothesis that each iterate of `fComp n` is convex.
-/
problem imc2011_p10 (n : ℕ) (hn : 2 ≤ n) (F : Polygon n)
    (hF : IsConvex F)
    (h_inter :
      ∀ m ≤ n, IsConvex ((fComp n)^[m] F)) :
    (fComp n)^[n] F = F := by
  -- Outline of the proof:
  -- 1. Show `fOp k ∘ fOp k = id` (involution).
  -- 2. Show `fOp k ∘ fOp j = fOp j ∘ fOp k` for `|k - j| ≥ 2`
  --    (commutation on disjoint vertex triples).
  -- 3. Show `(fOp k ∘ fOp (k+1))^3 = id` on convex polygons
  --    (the quadrilateral preservation argument).
  -- 4. Use the Coxeter presentation of `S_n` to deduce that the group
  --    generated by the `fOp k`'s is a quotient of `S_n`.
  -- 5. Compute that `(σ_1 σ_2 ⋯ σ_{n-1})^n = id` in `S_n`, since this is
  --    the n-th power of the n-cycle `(1 2 ⋯ n)`.
  -- TODO: complete the proof.
  sorry

end Imc2011P10
