/-
Copyright (c) 2026 The Compfiles Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Li Xuanji
-/

import Mathlib.Tactic

import ProblemExtraction

problem_file { tags := [.Algebra] }

/-!
# International Mathematical Competition 2024, Problem 4

Let `g` and `h` be two distinct elements of a group `G`, and let `n` be a
positive integer. Consider a sequence `w = (w₁, w₂, …)` which is not
eventually periodic and where each `wᵢ` is either `g` or `h`. Denote by
`H` the subgroup of `G` generated by all elements of the form
`w_k · w_{k+1} · … · w_{k+n-1}` with `k ≥ 1`. Prove that `H` does not
depend on the choice of the sequence `w` (but may depend on `n`).
-/

namespace Imc2024P4

open scoped Pointwise

variable {G : Type*} [Group G]

/-- A sequence `w : ℕ → G` is eventually periodic if there exist `N` and
`p > 0` such that `w (k + p) = w k` for all `k ≥ N`. -/
def EventuallyPeriodic (w : ℕ → G) : Prop :=
  ∃ N p : ℕ, 0 < p ∧ ∀ k ≥ N, w (k + p) = w k

/-- The `n`-gram at index `k` of the sequence `w` is the product
`w k · w (k+1) · … · w (k + n - 1)`. -/
def ngram (w : ℕ → G) (n k : ℕ) : G :=
  ((List.range n).map (fun i => w (k + i))).prod

/-- The subgroup generated by all `n`-grams of the sequence `w`. -/
noncomputable def ngramSubgroup (w : ℕ → G) (n : ℕ) : Subgroup G :=
  Subgroup.closure {x | ∃ k : ℕ, x = ngram w n k}

problem imc2024_p4 (G : Type*) [Group G] (g h : G) (hgh : g ≠ h) (n : ℕ)
    (hn : 0 < n) (w w' : ℕ → G)
    (hw_vals : ∀ k, w k = g ∨ w k = h)
    (hw'_vals : ∀ k, w' k = g ∨ w' k = h)
    (hw_np : ¬ EventuallyPeriodic w)
    (hw'_np : ¬ EventuallyPeriodic w') :
    ngramSubgroup w n = ngramSubgroup w' n := by
  -- TODO: Following the official solution.
  -- Let H_w be the subgroup for sequence w. We show H_w = H where H is
  -- the subgroup generated by all n-grams that appear in *some* {g,h}-word.
  -- Key step: Since w is not eventually periodic, by a pigeonhole argument
  -- every n-gram that occurs in some {g,h}-word (equivalently, every
  -- length-n word in {g,h}) actually appears as a factor of w, up to
  -- conjugation by shorter products. Then cross-compare w and w'.
  sorry

end Imc2024P4
